export type ResourcesSubjects = "READ/WRITE" |
"READ/WRITE-ATTRIBUTE" |
"READ/WRITE-OWNER" |
"READ-ATTRIBUTE/WRITE-ATTRIBUTE" |
"READ-ATTRIBUTE/WRITE-OWNER" |
"READ-OWNER/WRITE-OWNER" |
"READ" |
"READ-ATTRIBUTE" |
"READ-OWNER" |
"NONE";

export type RolesSubjects = "READ/WRITE";
