language: node_js
node_js: 8.11.1
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- npm run build
script:
- npm run test-all-cvr
after_success:
- npm run coverage
- npm run aftertests
