const CREATE = "Roles/CREATE";
const RESOURCE_ACCESSIBLE_MAKE = "Roles/RESOURCE_ACCESSIBLE_MAKE";
const RESOURCE_INACCESSIBLE_MAKE = "Roles/RESOURCE_INACCESSIBLE_MAKE";
const RESOURCE_PERMISSION_SET = "Roles/RESOURCE_PERMISSION_SET";
const RESOURCE_PERMISSION_DELETE = "Roles/RESOURCE_PERMISSION_DELETE";
const RESOURCE_SUBJECT_SET = "Roles/RESOURCE_SUBJECT_SET";
const RESOURCE_SUBJECT_DELETE = "Roles/RESOURCE_SUBJECT_DELETE";

export const ActionTypes = {
  CREATE,
  RESOURCE_ACCESSIBLE_MAKE,
  RESOURCE_INACCESSIBLE_MAKE,
  RESOURCE_PERMISSION_SET,
  RESOURCE_PERMISSION_DELETE,
  RESOURCE_SUBJECT_SET,
  RESOURCE_SUBJECT_DELETE,
};
