const CREATE = "Resources/CREATE";
const ACCESSIBLE_MAKE = "Resources/ACCESSIBLE_MAKE";
const INACCESSIBLE_MAKE = "Resources/INACCESSIBLE_MAKE";
const PERMISSION_SET = "Resources/PERMISSION_SET";
const PERMISSION_DELETE = "Resources/PERMISSION_DELETE";
const SUBJECT_SET = "Resources/SUBJECT_SET";
const SUBJECT_DELETE = "Resources/SUBJECT_DELETE";

export const ActionTypes = {
  CREATE,
  ACCESSIBLE_MAKE,
  INACCESSIBLE_MAKE,
  PERMISSION_SET,
  PERMISSION_DELETE,
  SUBJECT_SET,
  SUBJECT_DELETE,
};
